{{ if eq .Values.kind "Job" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include ".Chart.Name .fullname" $ }}-{{ randAlphaNum 5 | lower }}
  labels:
    app: {{ template ".Chart.Name .name" $ }}
    chart: {{ template ".Chart.Name .chart" $ }}
    release: {{ $.Release.Name }}
    releaseVersion: {{ $.Values.releaseVersion | quote }}
    pipelineName: {{ .Values.pipelineName }}
spec:
  backoffLimit: {{ .Values.jobConfigs.backoffLimit }}
  activeDeadlineSeconds: {{ .Values.jobConfigs.activeDeadlineSeconds }}
  parallelism: {{ .Values.jobConfigs.parallelism }}
  completions: {{ .Values.jobConfigs.completions }}
  {{- if semverCompare ">1.20" .Capabilities.KubeVersion.GitVersion -}}
  suspend: {{ .Values.jobConfigs.suspend }}
  {{- end }}
  ttlSecondsAfterFinished: {{ .Values.jobConfigs.ttlSecondsAfterFinished }}
  template:
    metadata:
    {{- if .Values.podAnnotations }}
      annotations:
      {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    {{- end }}
      labels:
        app: {{ template ".Chart.Name .name" $ }}
        appId: {{ $.Values.app | quote }}
        envId: {{ $.Values.env | quote }}
        release: {{ $.Release.Name }}
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
    spec:
      {{- include "pod-template-spec" . | indent 4 }}
{{ end }}
