{{- if .Values.ConfigSecrets.enabled }}
  {{- range .Values.ConfigSecrets.secrets }}
  {{if eq .external true }}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .name}}
spec:
  provider:
    {{- toYaml .secretStore | nindent 4 }}

---
apiVersion: external-secrets.io/v1beta1 
kind: ExternalSecret
metadata:
  name: {{ .name }}
spec:
  {{- if .refreshInterval }}
  refreshInterval: {{ .refreshInterval }}
  {{- else }}
  refreshInterval: 1h
  {{- end}}
  secretStoreRef:
    name: {{ .name}}
    kind: SecretStore
  target:
    name: {{ .name}}
    creationPolicy: Owner
  data:
  {{- range .esoData }}
  - secretKey: {{ .secretKey }}
    remoteRef:
        key: {{ .key }}
        property: {{ .property }} 
  {{- end}}
{{- end}}
{{- end}}
{{- end}}
