installer:
  release: "v0.6.9"
  image: "quay.io/devtron/inception"
  tag: "1d2b87e5-185-11095"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:693babcf-325-11957"
  devtron:
    image: "quay.io/devtron/hyperion:f07f89e1-280-11968"
    cicdImage: "quay.io/devtron/devtron:f07f89e1-326-11966"
  argocdDexServer:
    image: "ghcr.io/dexidp/dex:v2.30.2"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:6e466830-393-11943"
  kubelink:
    image: "quay.io/devtron/kubelink:2ae4e7a7-318-11969"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
    armImage: "quay.io/devtron/postgres:11.9"
  
  migrator:
    image: "quay.io/devtron/migrator:71748de9-149-11112"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "f07f89e1c89f9841d80aa35840a0e855b987f2f6"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "f07f89e1c89f9841d80aa35840a0e855b987f2f6"
        
argo-cd:
  global:
    image:
      repository: quay.io/argoproj/argocd
      tag: "v2.4.0"
      imagePullPolicy: IfNotPresent
      
notifier:
  image: "quay.io/devtron/notifier:6c7a356a-372-11107"
