installer:
  release: "v0.6.9"
  image: "quay.io/devtron/inception"
  tag: "1d2b87e5-185-11095"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:936f762a-325-11675"
  devtron:
    image: "quay.io/devtron/hyperion:9d012295-280-11681"
    cicdImage: "quay.io/devtron/devtron:9d012295-326-11680"
  argocdDexServer:
    image: "ghcr.io/dexidp/dex:v2.30.2"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:aecda793-393-11109"
  kubelink:
    image: "quay.io/devtron/kubelink:1d2cc28a-318-11533"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
    armImage: "quay.io/devtron/postgres:11.9"
  
  migrator:
    image: "quay.io/devtron/migrator:71748de9-149-11112"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "9d0122959f6424f3b846553de63532519e32caac"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "9d0122959f6424f3b846553de63532519e32caac"
        
argo-cd:
  global:
    image:
      repository: quay.io/argoproj/argocd
      tag: "v2.4.0"
      imagePullPolicy: IfNotPresent
      
notifier:
  image: "quay.io/devtron/notifier:6c7a356a-372-11107"
