global:
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
  containerSecurityContext:
    allowPrivilegeEscalation: false
    runAsUser: 1000
    runAsNonRoot: true

installer:
  release: "v0.6.20"
  image: "quay.io/devtron/inception"
  tag: "44b30917-185-13275"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:fc19ac0b-325-14837"
    config:
      extraConfigs:
        USE_V2: "true"
        ENABLE_BUILD_CONTEXT: "true"
        ENABLE_RESTART_WORKLOAD: "true"
  devtron:
    image: "quay.io/devtron/hyperion:a9757030-280-14883"
    cicdImage: "quay.io/devtron/devtron:a9757030-434-14884"
    customOverrides:
      DEFAULT_CI_IMAGE: "quay.io/devtron/ci-runner:71e590dd-138-14841"
  argocdDexServer:
    image: "ghcr.io/dexidp/dex:v2.30.2"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:e414faff-393-13273"
  kubelink:
    image: "quay.io/devtron/kubelink:af6112c2-318-14801"
    configs:
      ENABLE_HELM_RELEASE_CACHE: "true"
      PG_ADDR: postgresql-postgresql.devtroncd
      PG_DATABASE: orchestrator
      PG_LOG_QUERY: "true"
      PG_PORT: "5432"
      PG_USER: postgres
    dbconfig:
      secretName: postgresql-postgresql
      keyName: postgresql-password
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
    armImage: "quay.io/devtron/postgres:11.9"
  
  migrator:
    image: "quay.io/devtron/migrator:ec1dcab8-149-13278"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "a97570301f577d3f5c312085028e5d87bcfdda7d"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "a97570301f577d3f5c312085028e5d87bcfdda7d"
        
argo-cd:
  global:
    image:
      repository: quay.io/argoproj/argocd
      tag: "v2.5.2"
      imagePullPolicy: IfNotPresent

security:
  imageScanner:
    image: "quay.io/devtron/image-scanner:d554c0f8-334-14015"

notifier:
  image: "quay.io/devtron/notifier:d9c72180-372-14306"
