installer:
  release: "v0.6.10-rc.1"
  image: "quay.io/devtron/inception"
  tag: "1d2b87e5-185-11095"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:5d338cfb-325-12102"
  devtron:
    image: "quay.io/devtron/hyperion:119d1dfe-280-12127"
    cicdImage: "quay.io/devtron/devtron:b26f1f60-326-12128"
  argocdDexServer:
    image: "ghcr.io/dexidp/dex:v2.30.2"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:6e466830-393-11943"
  kubelink:
    image: "quay.io/devtron/kubelink:2ae4e7a7-318-11969"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
    armImage: "quay.io/devtron/postgres:11.9"
  
  migrator:
    image: "quay.io/devtron/migrator:71748de9-149-11112"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "b26f1f60cb00c0e7d1d4768ebe08543fe14913a0"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "b26f1f60cb00c0e7d1d4768ebe08543fe14913a0"
        
argo-cd:
  global:
    image:
      repository: quay.io/argoproj/argocd
      tag: "v2.4.0"
      imagePullPolicy: IfNotPresent
      
notifier:
  image: "quay.io/devtron/notifier:6c7a356a-372-11107"
