installer:
  release: "v0.6.8"
  image: "quay.io/devtron/inception"
  tag: "1d2b87e5-185-11095"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:3d202655-325-11844"
  devtron:
    image: "quay.io/devtron/hyperion:2753427a-280-11832"
    cicdImage: "quay.io/devtron/devtron:0164c1b8-326-11833"
  argocdDexServer:
    image: "ghcr.io/dexidp/dex:v2.30.2"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:461b5cb7-381-11808"
  kubelink:
    image: "quay.io/devtron/kubelink:1d2cc28a-318-11533"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
    armImage: "quay.io/devtron/postgres:11.9"
  
  migrator:
    image: "quay.io/devtron/migrator:71748de9-149-11112"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "0164c1b8fd9139520f02d291bc9e79b71baa1616"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "0164c1b8fd9139520f02d291bc9e79b71baa1616"
        
argo-cd:
  global:
    image:
      repository: quay.io/argoproj/argocd
      tag: "v2.4.0"
      imagePullPolicy: IfNotPresent
      
notifier:
  image: "quay.io/devtron/notifier:6c7a356a-372-11107"
