installer:
  release: "v0.6.10-rc.2"
  image: "quay.io/devtron/inception"
  tag: "1d2b87e5-185-11095"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:090c3dde-325-12132"
  devtron:
    image: "quay.io/devtron/hyperion:58dc922f-280-12136"
    cicdImage: "quay.io/devtron/devtron:fd3d51ac-326-12146"
  argocdDexServer:
    image: "ghcr.io/dexidp/dex:v2.30.2"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:6e466830-393-11943"
  kubelink:
    image: "quay.io/devtron/kubelink:7f9303ae-318-12150"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
    armImage: "quay.io/devtron/postgres:11.9"
  
  migrator:
    image: "quay.io/devtron/migrator:71748de9-149-11112"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "fd3d51ac5f084d863f24479c0e9ebc6911767ecc"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "fd3d51ac5f084d863f24479c0e9ebc6911767ecc"
        
argo-cd:
  global:
    image:
      repository: quay.io/argoproj/argocd
      tag: "v2.4.0"
      imagePullPolicy: IfNotPresent
      
notifier:
  image: "quay.io/devtron/notifier:6c7a356a-372-11107"
