installer:
  release: "v0.6.9-rc.0"
  image: "quay.io/devtron/inception"
  tag: "1d2b87e5-185-11095"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:925a1382-325-11762"
  devtron:
    image: "quay.io/devtron/hyperion:78b8a5ef-280-11769"
    cicdImage: "quay.io/devtron/devtron:78b8a5ef-326-11770"
  argocdDexServer:
    image: "ghcr.io/dexidp/dex:v2.30.2"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:aecda793-393-11109"
  kubelink:
    image: "quay.io/devtron/kubelink:1d2cc28a-318-11533"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
    armImage: "quay.io/devtron/postgres:11.9"
  
  migrator:
    image: "quay.io/devtron/migrator:71748de9-149-11112"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "78b8a5efb0cc1264a341e86ff8fb2eab1c95f61e"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "78b8a5efb0cc1264a341e86ff8fb2eab1c95f61e"
        
argo-cd:
  global:
    image:
      repository: quay.io/argoproj/argocd
      tag: "v2.4.0"
      imagePullPolicy: IfNotPresent
      
notifier:
  image: "quay.io/devtron/notifier:6c7a356a-372-11107"
