installer:
  release: "v0.6.7-rc.1"
  image: "quay.io/devtron/inception"
  tag: "1d2b87e5-185-11095"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:4960cda1-325-11597"
  devtron:
    image: "quay.io/devtron/hyperion:4079e379-280-11624"
    cicdImage: "quay.io/devtron/devtron:4079e379-326-11623"
  argocdDexServer:
    image: "ghcr.io/dexidp/dex:v2.30.2"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:aecda793-393-11109"
  kubelink:
    image: "quay.io/devtron/kubelink:1d2cc28a-318-11533"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
    armImage: "quay.io/devtron/postgres:11.9"
  
  migrator:
    image: "quay.io/devtron/migrator:71748de9-149-11112"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "4079e379f40ed16d5d2a6a2abdec181ba4272e15"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "4079e379f40ed16d5d2a6a2abdec181ba4272e15"
        
argo-cd:
  global:
    image:
      repository: quay.io/argoproj/argocd
      tag: "v2.4.0"
      imagePullPolicy: IfNotPresent
      
notifier:
  image: "quay.io/devtron/notifier:6c7a356a-372-11107"
