installer:
  release: "v0.4.28"
  image: "quay.io/devtron/inception"
  tag: "c62d4c30-185-9354"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:763622e7-325-10153"
  devtron:
    image: "quay.io/devtron/hyperion:72e36aff-280-9764"
    cicdImage: "quay.io/devtron/devtron:571e0fd6-326-10154"
  argocdDexServer:
    image: "quay.io/dexidp/dex:v2.25.0"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:415f5470-279-6520"
      cicdAuthenticator: "quay.io/argoproj/argocd:v1.8.1"
  kubelink:
    image: "quay.io/devtron/kubelink:59a0df88-318-9226"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
  
  migrator:
    image: "quay.io/devtron/migrator:6687f572-133-2208"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "571e0fd65664240104fe0b73c6fbcf0e73f084ef"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "571e0fd65664240104fe0b73c6fbcf0e73f084ef"
