installer:
  release: "v0.6.11-rc.0"
  image: "quay.io/devtron/inception"
  tag: "1d2b87e5-185-11095"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:77cc75b3-325-12238"
  devtron:
    image: "quay.io/devtron/hyperion:d37c1c14-280-12236"
    cicdImage: "quay.io/devtron/devtron:d37c1c14-326-12234"
  argocdDexServer:
    image: "ghcr.io/dexidp/dex:v2.30.2"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:6e466830-393-11943"
  kubelink:
    image: "quay.io/devtron/kubelink:7f9303ae-318-12204"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
    armImage: "quay.io/devtron/postgres:11.9"
  
  migrator:
    image: "quay.io/devtron/migrator:71748de9-149-11112"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "d37c1c14778542ff63006d673043f15fdde8a198"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "d37c1c14778542ff63006d673043f15fdde8a198"
        
argo-cd:
  global:
    image:
      repository: quay.io/argoproj/argocd
      tag: "v2.4.0"
      imagePullPolicy: IfNotPresent
      
notifier:
  image: "quay.io/devtron/notifier:6c7a356a-372-11107"
