installer:
  release: "v0.6.10-rc.1"
  image: "quay.io/devtron/inception"
  tag: "1d2b87e5-185-11095"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:370d092c-325-12068"
  devtron:
    image: "quay.io/devtron/hyperion:f9189d79-280-12076"
    cicdImage: "quay.io/devtron/devtron:f9189d79-326-12074"
  argocdDexServer:
    image: "ghcr.io/dexidp/dex:v2.30.2"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:6e466830-393-11943"
  kubelink:
    image: "quay.io/devtron/kubelink:2ae4e7a7-318-11969"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
    armImage: "quay.io/devtron/postgres:11.9"
  
  migrator:
    image: "quay.io/devtron/migrator:71748de9-149-11112"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "f9189d7904bd35d654f04438244fa7fb36aa1ec1"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "f9189d7904bd35d654f04438244fa7fb36aa1ec1"
        
argo-cd:
  global:
    image:
      repository: quay.io/argoproj/argocd
      tag: "v2.4.0"
      imagePullPolicy: IfNotPresent
      
notifier:
  image: "quay.io/devtron/notifier:6c7a356a-372-11107"
