global:
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
  containerSecurityContext:
    allowPrivilegeEscalation: false
    runAsUser: 1000
    runAsNonRoot: true

installer:
  release: "v0.6.14"
  image: "quay.io/devtron/inception"
  tag: "1d2b87e5-185-11095"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:de186b14-325-12876"
  devtron:
    image: "quay.io/devtron/hyperion:85c4a6d7-280-13270"
    cicdImage: "quay.io/devtron/devtron:85c4a6d7-434-13269"
  argocdDexServer:
    image: "ghcr.io/dexidp/dex:v2.35.3"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:6e466830-393-11943"
  kubelink:
    image: "quay.io/devtron/kubelink:d2406e8a-318-13263"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
    armImage: "quay.io/devtron/postgres:11.9"
  
  migrator:
    image: "quay.io/devtron/migrator:71748de9-149-11112"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "85c4a6d76492f9a1cc45360dd910f03fabac1b13"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "85c4a6d76492f9a1cc45360dd910f03fabac1b13"
        
argo-cd:
  global:
    image:
      repository: quay.io/argoproj/argocd
      tag: "v2.5.2"
      imagePullPolicy: IfNotPresent

security:
  image: "quay.io/devtron/image-scanner:b7873c95-334-13266"

notifier:
  image: "quay.io/devtron/notifier:6c7a356a-372-11107"
