installer:
  release: "v0.6.11-rc.0"
  image: "quay.io/devtron/inception"
  tag: "1d2b87e5-185-11095"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:b3f8068e-325-12250"
  devtron:
    image: "quay.io/devtron/hyperion:62ae4828-280-12262"
    cicdImage: "quay.io/devtron/devtron:62ae4828-326-12260"
  argocdDexServer:
    image: "ghcr.io/dexidp/dex:v2.30.2"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:6e466830-393-11943"
  kubelink:
    image: "quay.io/devtron/kubelink:7f9303ae-318-12204"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
    armImage: "quay.io/devtron/postgres:11.9"
  
  migrator:
    image: "quay.io/devtron/migrator:71748de9-149-11112"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "62ae48281c7ada2a02cb5e8fade406f6666fa6b3"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "62ae48281c7ada2a02cb5e8fade406f6666fa6b3"
        
argo-cd:
  global:
    image:
      repository: quay.io/argoproj/argocd
      tag: "v2.4.0"
      imagePullPolicy: IfNotPresent
      
notifier:
  image: "quay.io/devtron/notifier:6c7a356a-372-11107"
