installer:
  release: "v0.6.9-rc.1"
  image: "quay.io/devtron/inception"
  tag: "1d2b87e5-185-11095"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:925a1382-325-11772"
  devtron:
    image: "quay.io/devtron/hyperion:a8efbe0a-280-11799"
    cicdImage: "quay.io/devtron/devtron:a8efbe0a-326-11797"
  argocdDexServer:
    image: "ghcr.io/dexidp/dex:v2.30.2"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:aecda793-393-11109"
  kubelink:
    image: "quay.io/devtron/kubelink:1d2cc28a-318-11533"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
    armImage: "quay.io/devtron/postgres:11.9"
  
  migrator:
    image: "quay.io/devtron/migrator:71748de9-149-11112"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "a8efbe0ae401b5174e26d5e63afc4ed268f1df65"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "a8efbe0ae401b5174e26d5e63afc4ed268f1df65"
        
argo-cd:
  global:
    image:
      repository: quay.io/argoproj/argocd
      tag: "v2.4.0"
      imagePullPolicy: IfNotPresent
      
notifier:
  image: "quay.io/devtron/notifier:6c7a356a-372-11107"
