installer:
  release: "v0.6.2"
  image: "quay.io/devtron/inception"
  tag: "1d2b87e5-185-11095"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:9c21414c-325-10743"
  devtron:
    image: "quay.io/devtron/hyperion:cb0316cb-282-10980"
    cicdImage: "quay.io/devtron/devtron:1d654f24-326-11100"
  argocdDexServer:
    image: "ghcr.io/dexidp/dex:v2.30.2"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:aecda793-381-10540"
  kubelink:
    image: "quay.io/devtron/kubelink:919924e0-318-10747"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
  
  migrator:
    image: "quay.io/devtron/migrator:9c933d29-149-10140"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "1d654f247a545926bac39189eaa63309e9b6bbc7"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "1d654f247a545926bac39189eaa63309e9b6bbc7"
        
argo-cd:
  global:
    image:
      repository: quay.io/argoproj/argocd
      tag: "v2.4.0"
      imagePullPolicy: IfNotPresent
