installer:
  release: "v0.6.10-rc.2"
  image: "quay.io/devtron/inception"
  tag: "1d2b87e5-185-11095"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:a0511060-325-12158"
  devtron:
    image: "quay.io/devtron/hyperion:fd3d51ac-280-12152"
    cicdImage: "quay.io/devtron/devtron:14d4eebf-326-12162"
  argocdDexServer:
    image: "ghcr.io/dexidp/dex:v2.30.2"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:6e466830-393-11943"
  kubelink:
    image: "quay.io/devtron/kubelink:7f9303ae-318-12150"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
    armImage: "quay.io/devtron/postgres:11.9"
  
  migrator:
    image: "quay.io/devtron/migrator:71748de9-149-11112"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "14d4eebf8678fad7889bac74cd19babec49bdac6"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "14d4eebf8678fad7889bac74cd19babec49bdac6"
        
argo-cd:
  global:
    image:
      repository: quay.io/argoproj/argocd
      tag: "v2.4.0"
      imagePullPolicy: IfNotPresent
      
notifier:
  image: "quay.io/devtron/notifier:6c7a356a-372-11107"
