global:
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
  containerSecurityContext:
    allowPrivilegeEscalation: false
    runAsUser: 1000
    runAsNonRoot: true

installer:
  release: "v0.6.16"
  image: "quay.io/devtron/inception"
  tag: "44b30917-185-13275"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:9cf46373-325-13730"
  devtron:
    image: "quay.io/devtron/hyperion:a6ffadc2-280-13734"
    cicdImage: "quay.io/devtron/devtron:d8f2a5dc-434-13724"
  argocdDexServer:
    image: "ghcr.io/dexidp/dex:v2.30.2"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:e414faff-393-13273"
  kubelink:
    image: "quay.io/devtron/kubelink:f9ac85a1-318-13714"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
    armImage: "quay.io/devtron/postgres:11.9"
  
  migrator:
    image: "quay.io/devtron/migrator:ec1dcab8-149-13278"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "d8f2a5dc1179afeb125f51b3d0c4a5c799dfe5c9"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "d8f2a5dc1179afeb125f51b3d0c4a5c799dfe5c9"
        
argo-cd:
  global:
    image:
      repository: quay.io/argoproj/argocd
      tag: "v2.5.2"
      imagePullPolicy: IfNotPresent

security:
  image: "quay.io/devtron/image-scanner:b7873c95-334-13266"

notifier:
  image: "quay.io/devtron/notifier:6c7a356a-372-11107"
