installer:
  release: "v0.6.12"
  image: "quay.io/devtron/inception"
  tag: "1d2b87e5-185-11095"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:250c7c3f-325-12816"
  devtron:
    image: "quay.io/devtron/hyperion:c35045c2-280-12565"
    cicdImage: "quay.io/devtron/devtron:bef3eb35-434-12819"
  argocdDexServer:
    image: "ghcr.io/dexidp/dex:v2.30.2"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:6e466830-393-11943"
  kubelink:
    image: "quay.io/devtron/kubelink:a5e179d4-318-12564"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
    armImage: "quay.io/devtron/postgres:11.9"
  
  migrator:
    image: "quay.io/devtron/migrator:71748de9-149-11112"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "bef3eb35bfc5cc530d2f8c53425e10905b6e9d90"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "bef3eb35bfc5cc530d2f8c53425e10905b6e9d90"
        
argo-cd:
  global:
    image:
      repository: quay.io/argoproj/argocd
      tag: "v2.4.0"
      imagePullPolicy: IfNotPresent
      
notifier:
  image: "quay.io/devtron/notifier:6c7a356a-372-11107"
