openapi: "3.0.0"
info:
  title: Jobs
  version: "1.0"
paths:
  /orchestrator/app/jobs:
    post:
      description: Create and clones a job
      requestBody:
        required: true
        content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/CreateJob"
      responses:
        "200 OK":
          description: Used to give response once a job is created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ActionResponse"
  /orchestrator/app/jobs/list:
    get:
      description: Get the list of all the jobs by applying filter
      requestBody:
        required: true
        content:
          application/json:
            schema:
              items:
                $ref: "#/components/schemas/JobList"

#components
components:
  schemas:
    CreateJob:
      type: object
      properties:
         appName:
           type: string
           description: Used to give the name of the job
           example: "my-job-1"
         teamId:
           type: integer
           description: Used to give team id
           example: 1
         templateId:
           type: integer
           description: Used to give the id of the job it wants to clone
           example: 18
         labels:
           type: []label
             label:
               key:
                 type: string
                 example: "hello"
               value:
                 type: string
                 example: "world"
               propogate:
                  type: bool
                  example: false
         description:
           type: string
           description: Used to give the description of the job once it is made.
           example: "This is my first Job"
         isJob:
           type: boolean
           description: Used to state whether it is an app or a job
           example: true
    ActionResponse:
      name: result
      type: object
      properties:
        id:
          type:  integer
          description: Used to give the id of job once its created
          example: 25
        appName:
          type: string
          description: Used to give the name of job once its created
          example: "my-job-1"
        material:
          type: []gitMaterial
            gitMaterial:
              name:
                type: string
              url:
                type: string
              id:
                type: integer
              gitProviderId:
                type: integer
              checkoutPath:
                type: string
              fetchSubmodules:
                type: bool
              isUsedInCiConfig:
                type: bool
          teamId:
            type: integer
            description: Used to give the team id
            example: 1
          templateId:
            type: integer
            description: Used to give the templateId
            example: 0
          description:
            type: string
            description: Used to give the description of the job once it is made.
            example: "This is my first Job"
          isJob:
            type: boolean
            description: used to tell whether it is a job or an app
            example: true
    JobList:
      type: object
      properties:






