openapi: "3.0.0"
info:
  version: 1.0.0
  title: Historical Task definitions - get api changes
paths:
  /orchestrator/app/history/deployed-configuration/detail/{appId}/{pipelineId}/{wfrId}:
    get:
      operationId: FetchHistoryDetail
      parameters:
        - name: appId
          in: path
          required: true
          schema:
            type: integer
        - name: pipelineId
          in: path
          required: true
          schema:
            type: integer
        - name: wfrId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successfully return history detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HistoryConfigurationDetailDto'
        '400':
          description: Bad Request. Input Validation error/wrong request body.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Unauthorized User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    HistoryConfigurationDetailDto:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          enum:
            - "DEPLOYMENT_TEMPLATE"
            - "CONFIGMAP"
            - "SECRET"
            - "PIPELINE_STRATEGY"
        childList:
          type: object
          properties:
            childName:
              $ref: '#/components/schemas/HistoryComponentChildDetailDto'
    HistoryComponentChildDetailDto:
      type: object
      properties:
        componentName:
          type: object
          properties:
            fieldName:
              type: string
            fieldName2:
              type: string
            codeEditorValue:
              type: object
              properties:
                displayName:
                  type: string
                value:
                  type: string