{{- define "rollout-template-spec" }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include ".Chart.Name .fullname" $ }}
  labels:
    app: {{ template ".Chart.Name .name" $ }}
    chart: {{ template ".Chart.Name .chart" $ }}
    release: {{ $.Release.Name }}
    releaseVersion: {{ $.Values.releaseVersion | quote }}
    pipelineName: {{ .Values.pipelineName }}
{{- if .Values.rolloutLabels }}
{{ toYaml .Values.rolloutLabels | indent 4 }}
{{- end }}
{{- if .Values.appLabels }}
{{ toYaml .Values.appLabels | indent 4 }}
{{- end }}
{{- if .Values.rolloutAnnotations }}
  annotations:
{{ toYaml .Values.rolloutAnnotations | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template ".Chart.Name .name" $ }}
      release: {{ $.Release.Name }}
  replicas: {{ $.Values.replicaCount }}
  minReadySeconds: {{ $.Values.MinReadySeconds }}
  template:
    {{- include "pod-template-spec" . | indent 4 }}
  revisionHistoryLimit: 3
##  pauseForSecondsBeforeSwitchActive: {{ $.Values.pauseForSecondsBeforeSwitchActive }}
#  waitForSecondsBeforeScalingDown: {{ $.Values.waitForSecondsBeforeScalingDown }}
  strategy:
    {{- if eq .Values.deploymentType "BLUE-GREEN" }}
    blueGreen: # A new field that used to provide configurable options for a BlueGreenUpdate strategy
      previewService: {{ template ".previewservicename" . }} # Reference to a service that can serve traffic to a new image before it receives the active traffic
      activeService: {{ template ".servicename" . }} # Reference to a service that serves end-user traffic to the replica set
      autoPromotionSeconds: {{ $.Values.deployment.strategy.blueGreen.autoPromotionSeconds  }}
      scaleDownDelaySeconds: {{ $.Values.deployment.strategy.blueGreen.scaleDownDelaySeconds }}
      previewReplicaCount: {{ $.Values.deployment.strategy.blueGreen.previewReplicaCount  }}
      autoPromotionEnabled: {{ $.Values.deployment.strategy.blueGreen.autoPromotionEnabled  }}
    {{- else if eq .Values.deploymentType "ROLLING" }}
    canary:
      stableService: {{ template ".servicename" . }} # Reference to a service that serves end-user traffic to the replica set
      maxSurge: {{ $.Values.deployment.strategy.rolling.maxSurge }}
      maxUnavailable: {{ $.Values.deployment.strategy.rolling.maxUnavailable }}
    {{- else if eq .Values.deploymentType "RECREATE" }}
    recreate:
      activeService: {{ template ".servicename" . }} # Reference to a service that serves end-user traffic to the replica set
    {{- else if eq .Values.deploymentType "CANARY" }}
    canary:
      stableService: {{ template ".servicename" . }} # Reference to a service that serves end-user traffic to the replica set
      maxSurge: {{ $.Values.deployment.strategy.canary.maxSurge }}
      maxUnavailable: {{ $.Values.deployment.strategy.canary.maxUnavailable }}
      steps:
{{ toYaml .Values.deployment.strategy.canary.steps | indent 8 }}
    {{- end }}
{{- end }}